project_id = "eeryrwdawoqggtpeckse"

[functions.worker-push]
verify_jwt = false

[functions.worker-pull]
verify_jwt = false

[functions.parse-signal]
verify_jwt = false

[functions.trade-executor]
verify_jwt = false
